# docker-compose.yml
version: '3'

services:
  # Backend API
  recommendation-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - DEBUG=false
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend webapp
  recommendation-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://recommendation-api:8000
      - FLASK_ENV=production
    depends_on:
      - recommendation-api
    restart: always